### ISSUE TITLE
Implicit innerJoin table name typo gives confusing error message

### ISSUE THREAD

**Issue by joelwat** [benbotto/node-data-mapper#3]
If you make a typo when using implicit innerJoins, you get a confusing error message
> Error: miss_typed_table_name is not indexed.

In From.js on line #134 it tries to get the foreign key relationships using `relStore.getRelationShips()` without checking if the table exists which is `meta.table`. It would be better if the error message said that the table doesn't exists instead of that it's not indexed.

**Comment by benbotto** [comment]
Thanks for the report.  I added better error handling for that case, and now you'll get an error message that says, "The joined-in table "<table-name>" is invalid."  Fixed in this commit: https://github.com/benbotto/node-data-mapper/commit/ad9cbeadcbf7bb217b8a973381f9300e678c7ee4 and published as 1.1.27.
